a/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'a'
urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^booking/$', views.booking, name='booking'),
    url(r'^carwash/$', views.carwash, name='carwash'),
    url(r'^washer/$', views.washer, name='washer'),

    url(r'^pricing/$', TemplateView.as_view(template_name='pricing.html'), name='pricing'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^insurance/$', TemplateView.as_view(template_name='insurance.html'), name='insurance'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),

    url(r'^accounts/dashboard/$', views.dashboard, name='dashboard'),
    url(r'^accounts/profile/$', views.profile, name='profile'),

    url(r'^accounts/profile/changerole/$', views.admin_change_role, name='admin_change_role')

]

as/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('a.urls', namespace='u')),
    url(r'^accounts/', include('allauth.urls')),
]

a/models.py
from django.db import models
from django.utils import timezone

from django.contrib.auth.models import AbstractUser


class BaseUser(AbstractUser):
    ROLE_CHOICES = [
        ('user', 'user'),
        ('washee', 'washee'),
        ('washer', 'washer'),
        ('both', 'both'),
    ]
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='user')
    phone = models.CharField(max_length=20, null=True, blank=True)
    rating = models.FloatField(null=True, blank=True)


class Washer(models.Model):
    baseUser = models.OneToOneField(BaseUser)

    approved = models.BooleanField(default=False)
    has_car = models.BooleanField(default=False)
    has_hose = models.BooleanField(default=False)
    travel_distance = models.IntegerField(default=0, blank=True)
    vacuum_type = models.CharField(max_length=40, blank=True)
    availability = models.CharField(max_length=255, blank=True)
    experience = models.CharField(max_length=2000, blank=True)

    def __str__(self):
        return self.baseUser.username


class Promocode(models.Model):
    code = models.CharField(max_length=40)
    available = models.BooleanField(default=True)
    usage = models.IntegerField(default=0)
    max_usage = models.IntegerField(null=True, blank=True, default=1)
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(null=True, blank=True)
    DISCOUNT_CHOICES = [
        ('%', 'percentage'),
        ('$', 'amount'),
    ]
    discount_type = models.CharField(max_length=1, choices=DISCOUNT_CHOICES, default='$')
    discount = models.FloatField(default=0)

    def __str__(self):
        return self.code + ' ' + str(self.discount)


class Address(models.Model):
    baseUser = models.OneToOneField(BaseUser, null=True, blank=True)

    street_address = models.CharField(max_length=200, null=True, blank=True)
    suburb = models.CharField(max_length=40, null=True, blank=True)
    city = models.CharField(max_length=40, null=True, blank=True)
    postcode = models.CharField(max_length=10, blank=True, null=True)
    state = models.CharField(max_length=20, null=True, blank=True)
    country = models.CharField(max_length=40, null=True, blank=True)

    oneline_address = models.CharField(max_length=200, null=True, blank=True)
    formatted = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        if self.oneline_address:
            return self.oneline_address
        else:
            return self.street_address + ', ' + self.suburb + ' ' + self.postcode


class WashRequest(models.Model):
    washee = models.ForeignKey(BaseUser, on_delete=models.CASCADE, null=True, blank=True,
                               related_name='assigned_washee')

    address = models.ForeignKey(Address, null=True, blank=True)

    washer = models.ForeignKey(BaseUser, on_delete=models.CASCADE, null=True, blank=True,
                               related_name='assigned_washer')

    promocode = models.ForeignKey(Promocode, on_delete=models.CASCADE, null=True, blank=True)

    STATUS_CHOICES = [
        (1, 'Payment Pending'),
        (2, 'Arranging Washer'),
        (3, 'Wash in Progress'),
        (4, 'Completed'),
        (0, 'Cancelled'),
    ]
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    active = models.BooleanField(default=True)

    request_date = models.DateTimeField(null=True, blank=True)
    wash_date = models.DateTimeField(null=True, blank=True)
    water_details = models.CharField(max_length=40, null=True, blank=True)
    electricity_details = models.CharField(max_length=40, null=True, blank=True)
    vacuum_details = models.CharField(max_length=40, null=True, blank=True)
    description = models.CharField(max_length=254, null=True, blank=True)
    discount = models.FloatField(default=0, blank=True)
    car_count = models.IntegerField(default=1, blank=True)
    total_price = models.FloatField(default=0, blank=True)

    def __str__(self):
        return 'wash no.' + str(self.id)


class Car(models.Model):
    washRequest = models.ForeignKey(WashRequest, null=True)

    specs = models.CharField(max_length=40, null=True, blank=True)
    number_plate = models.CharField(max_length=10, null=True, blank=True)
    TYPE_CHOICES = [
        ('Hatchback', 'Hatchback'),
        ('Sedan', 'Sedan'),
        ('Wagon', 'Wagon'),
        ('SUV', 'SUV'),
        ('Van', 'Van'),
    ]
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, default='Sedan')
    dirtiness = models.IntegerField(null=True, blank=True)
    extra_dirty = models.BooleanField(default=False)
    vacuum = models.BooleanField(default=True)
    wiping = models.BooleanField(default=True)
    price = models.FloatField(default=0)

    def __str__(self):
        if self.specs:
            return self.specs
        else:
            return self.type


class BankAccount(models.Model):
    baseUser = models.OneToOneField(BaseUser)

    bank_name = models.CharField(max_length=40, null=True, blank=True)
    bsb = models.IntegerField(null=True, blank=True)
    account_number = models.IntegerField(null=True, blank=True)
    account_holder = models.CharField(max_length=40, null=True, blank=True)

    def __str__(self):
        return self.bank_name

templates/base.html
<html lang="en">

<head>
    <title>AirSponge | {% block head_title %}{% endblock %}</title>

    {% include 'meta.html' %}
    {% include 'css.html' %}
    {% block css %}{% endblock %}


</head>


<body {% block body-class %}{% endblock %}>

{% block nav %}
    {% include 'nav.html' %}
{% endblock %}

{% block content %}{% endblock %}

{% include 'footer.html' %}

{% include 'js.html' %}


</body>

</html>

templates/booking.html
{% extends 'base.html' %}

{% load customtags %}

{% load staticfiles %}

{% block head_title %}
    Booking
{% endblock %}

{% block body-class %}
    class="booking-page" onload="assignInitialValues(
    {% if initial_type_choice and initial_interior_choice %}
        '{{ initial_type_choice }}', '{{ initial_interior_choice }}'
    {% endif %}
    );"
{% endblock %}


{% block content %}
    <div class="headline-bg booking-headline-bg">
    </div><!--//headline-bg-->

    <section class="booking-section custom-section section section-on-bg">
        <div class="container">
            <h2 class="title text-center">Request Carwash</h2>

            <form class="booking-form" method="POST" action="">
                {% csrf_token %}
                <div class="row">
                    <div class="section-inner col-md-6 col-md-offset-3 col-sm-12">
                        {% if message %}
                            <div class="col-sm-12">
                                <p class="inner-section-title error-message">{{ message }}</p>
                            </div>
                        {% endif %}
                        <div class="row form-profile">
                            <div class="col-sm-12">
                                <h3 class="inner-section-title">Profile</h3>
                            </div>
                            {% include 'form-field.html' with field=form.first_name_field class='col-sm-6' %}
                            {% include 'form-field.html' with field=form.last_name_field class='col-sm-6' %}
                            {% include 'form-field.html' with field=form.phone_field class='col-sm-12' %}
                            {% include 'form-field.html' with field=form.email_field class='col-sm-12' %}
                        </div>
                        <div class="row form-wash-request">
                            <div class="col-sm-12">
                                <h3 class="inner-section-title">Carwash Request</h3>
                            </div>
                            {% include 'form-field.html' with field=form.street_address_field class='col-sm-12' %}
                            {% include 'form-field.html' with field=form.suburb_field class='col-sm-6 col-xs-12' %}
                            {% include 'form-field.html' with field=form.state_field class='col-sm-3 col-xs-6' %}
                            {% include 'form-field.html' with field=form.postcode_field class='col-sm-3 col-xs-6' %}
                            {% include 'form-field.html' with field=form.wash_date_field class='col-sm-12' %}
                            {% include 'form-field.html' with field=form.promocode_field class='col-sm-12' %}
                        </div>
                        <div class="row form-car-details">
                            <div class="col-sm-12">
                                <h3 class="inner-section-title">Car Details</h3>
                                <p id="total-price">$0</p>
                            </div>
                            {{ form.car_count_field }}
                            {% for car in form.booking.cars %}
                                <div id="car{{ car }}"
                                     {% if car != '1' %}class="row no-margin car-divs"
                                     {% else %}class="row no-margin"{% endif %}>
                                    {% include 'form-field.html' with field=form|get_car_specs_field:car class='col-sm-12' %}
                                    {% include 'form-field.html' with field=form|get_type_field:car class='col-sm-5' %}
                                    {% include 'form-field.html' with field=form|get_interior_field:car class='col-sm-7' %}
                                    {% include 'form-field.html' with field=form|get_extra_dirty_field:car label='after' class='col-sm-12 form-group-extra-dirty' %}
                                </div>
                            {% endfor %}
                            <div class="col-sm-12 form-group text-center">
                                <a id="remove_car_btn" type="button" class="btn btn-default" onclick="removeCar(this);"
                                   style="display: none"><span class="glyphicon glyphicon-minus"></span></a>
                                <a id="add_car_btn" type="button" class="btn btn-default" onclick="addCar(this);">
                                    <span class="glyphicon glyphicon-plus"></span></a>
                            </div>
                        </div>
                        <div class="row form-submit">
                            <div class="col-sm-12 form-group">
                                <button id="booking-submit"
                                        class="btn btn-cta btn-cta-primary btn-block btn-form-submit" type="submit">
                                    Submit Request
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

templates/carwash.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head_title %}
    Payment
{% endblock %}

{% block body-class %}
    class='washrequest-page'
{% endblock %}

{% block content %}
    <div class="headline-bg payment-headline-bg">
    </div><!--//headline-bg-->

    <section class="washrequest-section custom-section section section-on-bg">
        <div class="container">
            <h2 class="title text-center">Wash Request #{{ wash_request.id }}</h2>
            <div class="row">
                <div class="section-inner col-md-6 col-md-offset-3 col-sm-12">
                    <div class="row request">
                        <div class="col-sm-12">
                            <h3 class="inner-section-title">Request</h3>
                            {% if user.role == 'washee' or user.role == 'both' %}
                                {% if wash_request.status > 0 and wash_request.status < 4 %}
                                    <a id='cancel-carwash-btn' class="request-action" href="#">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </a>
                                {% endif %}
                                {% if wash_request.status == 1 %}
                                    <a class="request-action" href="{% url 'a:booking' %}?id={{ wash_request.id }}">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </a>
                                {% endif %}
                            {% endif %}

                        </div>
                        <div class="col-sm-12">
                            <table class="table-condensed">
                                <tr>
                                    <th>Status:</th>
                                    <td>{{ wash_request.get_status_display }}</td>
                                </tr>
                                <tr>
                                    <th>Name:</th>
                                    <td>{{ wash_request.washee.first_name }} {{ wash_request.washee.last_name }}</td>
                                </tr>
                                <tr>
                                    <th>Phone:</th>
                                    <td>{{ wash_request.washee.phone }}</td>
                                </tr>
                                <tr>
                                    <th>Email:</th>
                                    <td>{{ wash_request.washee.email }}</td>
                                </tr>
                                <tr>
                                    <th>Address:</th>
                                    <td>{{ wash_request.address.oneline_address }}</td>
                                </tr>
                                <tr>
                                    <th>Wash Date:</th>
                                    <td>{{ wash_request.wash_date }}</td>
                                </tr>
                                {% if wash_request.promocode %}
                                    <tr>
                                        <th>Promocode:</th>
                                        <td>{{ wash_request.promocode.code }}</td>
                                    </tr>
                                    <tr>
                                        <th>Discount:</th>
                                        <td>${{ wash_request.discount }}</td>
                                    </tr>
                                {% endif %}
                                <tr>
                                    <th>Total:</th>
                                    <td>${{ wash_request.total_price }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="row cars">
                        {% for car in wash_request.car_set.all %}
                            <div class="col-sm-12">
                                <h3 class="inner-section-title">{{ car.specs }}</h3>
                                <table class="table-condensed">
                                    <tr>
                                        <td>
                                            {{ car.type }}
                                        </td>
                                    </tr>
                                    {% if car.wiping %}
                                        <tr>
                                            <td>Interior wipe</td>
                                        </tr>
                                    {% endif %}
                                    {% if car.vacuum %}
                                        <tr>
                                            <td>Interior vacuum</td>
                                        </tr>
                                    {% endif %}
                                    {% if car.extra_dirty %}
                                        <tr>
                                            <td>
                                                Extra dirty
                                            </td>
                                        </tr>
                                    {% endif %}

                                    <tr>
                                        <td>
                                            ${{ car.price }}
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        {% endfor %}
                    </div>
                    {% if wash_request.status == 1 and user.role == 'washee' %}
                        <div class="form-group paypal-form text-center">

                            <form action="https://www.paypal.com/cgi-bin/webscr" method="post">

                                <!-- Identify your business so that you can collect the payments. -->
                                <input type="hidden" name="business" value="areej@airsponge.com">

                                <!-- Specify a Buy Now button. -->
                                <input type="hidden" name="cmd" value="_xclick">

                                <!-- Specify details about the item that buyers will purchase. -->
                                <input type="hidden" name="item_name" value="One time carwash">
                                <input type="hidden" name="return" value="{% url 'a:carwash' %}">
                                <input type="hidden" name="amount" value={{ wash_request.total_price }}>
                                <input type="hidden" name="currency_code" value="AUD">

                                <!-- Display the payment button. -->
                                <input type="image" name="submit" border="0"
                                       src="https://www.paypalobjects.com/en_US/i/btn/btn_xpressCheckout2.gif"
                                       alt="PayPal - The safer, easier way to pay online">
                                <img alt="" border="0" width="1" height="1"
                                     src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif">

                            </form>
                        </div>
                    {% endif %}
                    {% if user.role == 'both' %}
                        <div class="form-group paypal-form text-center">

                            <form action="https://www.paypal.com/cgi-bin/webscr" method="post">

                                <!-- Identify your business so that you can collect the payments. -->
                                <input type="hidden" name="business" value="areej@airsponge.com">

                                <!-- Specify a Buy Now button. -->
                                <input type="hidden" name="cmd" value="_xclick">

                                <!-- Specify details about the item that buyers will purchase. -->
                                <input type="hidden" name="item_name" value="One time carwash">
                                <input type="hidden" name="return" value="http://localhost:8000{% url 'a:carwash' %}">
                                <input type="hidden" name="amount" value=0.01>
                                <input type="hidden" name="currency_code" value="AUD">

                                <!-- Display the payment button. -->
                                <input type="image" name="submit" border="0"
                                       src="https://www.paypalobjects.com/en_US/i/btn/btn_xpressCheckout2.gif"
                                       alt="PayPal - The safer, easier way to pay online">
                                <img alt="" border="0" width="1" height="1"
                                     src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif">

                            </form>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    {% if wash_request.status > 0 and wash_request.status < 4 %}
        <form id="cancel-carwash-form" method="POST" action="">
            {% csrf_token %}
            <input id="id_washrequest_id" name="washrequest_id" type="hidden" value={{ wash_request.id }}>
        </form>
    {% endif %}
{% endblock %}

templates/footer.html
<!-- ******FOOTER****** -->
<footer class="footer">
    <div class="footer-content">
        <div class="container">
            <div class="row">
                <div class="footer-col connect col-md-6 col-sm-12 col-xs-12">
                    <div class="footer-col-inner">
                        <ul class="social list-inline">
                            <li><a href="https://twitter.com/airspongeco" target="_blank"><i
                                    class="fa fa-twitter"></i></a></li>
                            <li><a href="https://www.facebook.com/airspongeco/"><i class="fa fa-facebook"></i></a></li>
                        </ul>
                        <div class="form-container">
                            <p class="intro">Stay up to date with the latest news and offers from AirSponge</p>
                            <form class="signup-form navbar-form">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Enter your email address">
                                </div>
                                <button type="submit" class="btn btn-cta btn-cta-primary">Subscribe Now</button>
                            </form>
                        </div><!--//subscription-form-->
                    </div><!--//footer-col-inner-->
                </div><!--//foooter-col-->
                <div class="footer-col links col-md-3 col-sm-6 col-xs-12">
                    <div class="footer-col-inner">
                        <h3 class="title">About us</h3>
                        <ul class="list-unstyled">
                            <li><a href="{% url 'a:about' %}"><i class="fa fa-caret-right"></i>Who we are</a></li>
                            <li><a href="{% url 'a:contact' %}"><i class="fa fa-caret-right"></i>Contact us</a></li>
                        </ul>
                    </div><!--//footer-col-inner-->
                </div><!--//foooter-col-->
                <div class="footer-col contact col-md-3 col-sm-6 col-xs-12">
                    <div class="footer-col-inner">
                        <h3 class="title">Contact us</h3>
                        <p class="adr clearfix">
                            <i class="fa fa-map-marker pull-left"></i>
                                <span class="adr-group pull-left">
                                    <span class="place">Building 1015, Gate 4</span><br>
                                    <span class="street-address">80-120 Meiers Road</span><br>
                                    <span class="region">Indooroopilly, QLD</span><br>
                                    <span class="postal-code">4068</span><br>
                                    <span class="country-name">Aurstralia</span>
                                </span>
                        </p>
                        <p class="tel"><i class="fa fa-phone"></i>+61 434 192 769</p>
                        <p class="email"><i class="fa fa-envelope-o"></i><a href="#">info@airsponge.com.au</a></p>
                        <a href="https://twitter.com/airspongeco" class="twitter-follow-button"
                           data-show-count="false">Follow @3rdwave_themes</a>
                        <script>!function (d, s, id) {
                            var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https';
                            if (!d.getElementById(id)) {
                                js = d.createElement(s);
                                js.id = id;
                                js.src = p + '://platform.twitter.com/widgets.js';
                                fjs.parentNode.insertBefore(js, fjs);
                            }
                        }(document, 'script', 'twitter-wjs');</script>
                    </div><!--//footer-col-inner-->
                </div><!--//contact-->
                <div class="clearfix"></div>
            </div><!--//row-->
            <div class="row has-divider">

            </div>
        </div><!--//container-->
    </div><!--//footer-content-->
    <div class="bottom-bar">
        <div class="container">
            <small class="copyright">Copyright @ 2016 | AirSponge</small>
        </div><!--//container-->
    </div><!--//bottom-bar-->
</footer><!--//footer-->

templates/meta.html
{% block meta %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description"
          content="AirSponge">
    <meta name="author" content="Trynottobea*unt">
    <meta name="keywords" content="carwash">
{% endblock %}

templates/nav-role.html
<li>
    <a id="admin-{{ role }}" class="admin-change-role-btn" href="#">
        <span id="admin-{{ role }}-selector">
            {% if user.role == role %}
                >
            {% endif %}
        </span>
        {{ role }}
    </a>
</li>

templates/nav.html
<header id="header{{ none }}" class="header navbar-fixed-top {{ scrolled }}">
    <div>
        <div class="branding">
            <h1 class="logo">
                <a href="/"><span class="text">AirSponge</span></a>
            </h1><!--//logo-->
        </div>
        <nav class="main-nav navbar-right" role="navigation">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button><!--//nav-toggle-->
            </div><!--//navbar-header-->
            <div id="navbar-collapse" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    {% if user.role != 'washer' %}
                        <li class="nav-item nav-item-cta">
                            <a class="btn btn-cta btn-cta-secondary no-border-radius" href="{% url 'a:booking' %}">Book
                                a
                                Carwash</a>
                        </li>
                    {% endif %}
                    {% if not user.is_authenticated or user.role == 'user' %}
                        <li class="nav-item nav-item-cta">
                            <a class="btn btn-cta btn-cta-secondary no-border-radius" href="{% url 'a:washer' %}">Become
                                a
                                Washer</a>
                        </li>
                    {% endif %}
                    {#                    <li class="nav-item {{ pricing_active }}"><a href="{% url 'a:pricing' %}">Pricing</a></li>#}
                    {#                    <li class="nav-item {{ insurance_active }}"><a href="{% url 'a:insurance' %}">Insurance</a></li>#}
                    {#                    <li class="nav-item {{ about_active }}"><a href="{% url 'a:about' %}">About Us</a></li>#}
                    {#                    <li class="nav-item {{ contact_active }}"><a href="{% url 'a:contact' %}">Contact Us</a></li>#}
                    {% if user.is_authenticated %}
                        {% if user.is_superuser %}
                            <li class="nav-item nav-item-cta dropdown">
                                <a data-toggle="dropdown"
                                   data-hover="dropdown" data-delay="0"
                                   data-close-others="false" href="#">
                                    {{ user.role }}
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="dropdown-menu">
                                    {% if user.is_superuser %}
                                        {% include 'nav-role.html' with role='user' %}
                                        {% include 'nav-role.html' with role='washer' %}
                                        {% include 'nav-role.html' with role='washee' %}
                                        {% include 'nav-role.html' with role='both' %}
                                    {% endif %}
                                </ul>
                            </li>
                        {% endif %}
                        <li class="nav-item nav-item-cta last dropdown">
                            <a data-toggle="dropdown"
                               data-hover="dropdown" data-delay="0"
                               data-close-others="false" href="#">
                                {% if user.first_name %}
                                    {{ user.first_name }}
                                {% else %}
                                    {{ user.username }}
                                {% endif %}
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu">

                                {% if user.role != 'user' %}
                                    <li><a href="{% url 'a:dashboard' %}">Dashboard</a></li>
                                {% endif %}
                                <li><a href="{% url 'a:profile' %}">Profile</a></li>
                                <li><a href="{% url 'account_logout' %}">Log out</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item"><a href="{% url 'account_login' %}">Log in</a></li>
                        <li class="nav-item nav-item-cta last">
                            <a href="{% url 'account_signup' %}">Sign
                                Up</a>
                        </li>
                    {% endif %}


                </ul><!--//nav-->
            </div><!--//navabr-collapse-->
        </nav><!--//main-nav-->
    </div><!--//container-->
</header><!--//header-->

{% if user.is_superuser %}
    <form id="admin-change-role-form" method="POST" action="{% url 'a:admin_change_role' %}">
        {% csrf_token %}
        <input id="id_role_field" name="role_field" type="hidden" value="{{ user.role }}">
    </form>
{% endif %}